name: Feature CI
on: 
  push:
    branches:
      - "feature/**"
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: frontend/
      - name: Upload backend
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: backend/
  Build-Backend:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: golang:1.19-alpine
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: .
      - name: Build Binary
        run: go build backend/
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: backend-binary
          path: backend
  Build-Frontend:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: golang:1.19-alpine
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: .
      - name: Build Binary
        run: go build frontend/
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: frontend-binary
          path: frontend
        