name: Staging CI
on:
  pull_request:
    branches:
      - 'Staging'
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload frontend
        uses: actions/Upload-artifact@v2
        with:
          name: frontend
          path: frontend/
      - name: Upload backend
        uses: actions/Upload-artifact@v2
        with: 
          name: backend
          path: backend/
      - name: Upload kubernetes
        uses: action/upload-artifact@v2
        with:
          name: kubernetes
          path: kubernetes/
  Build-backend:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: golang:1.19-alpine
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: backend
          path: .
      - name: Download Redigo
        run: go mod download github.com/gomodule/redigo
      - name: Build Binary
        run: go build backend/
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: backend-binary
          path: backend
  Build-Frontend:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: golang:1.19-alpine
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: .
      - name: Build Binary
        run: go build frontend/
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: frontend-binary
          path: frontend
  Test:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: golang:1.19-alpine
    steps:
    - name: Download code
      uses: actions/Download-artifact@v2
      with:
        name: code
        path: .
    - name: Test
      run: ls
    - name: Upload
      uses: actions/Upload-artifact@v2
      with:
        name: code
        path: .